name: Notifier

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  messageWhatsApp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install Twilio CLI
        run: |
          npm install -g twilio-cli
      - name: Notification WhatsApp
        id: whatsapp-notify
        env:
          account_sid: ${{ secrets.twilio_account_sid }}
          auth_token: ${{ secrets.twilio_auth_token }}
          to_whatsapp_no: ${{ secrets.twilio_to_whatsapp_no }}
          message: "CI 👉🏻 Committer: ${{ github.actor }} pushed changes."
        run: |
          twilio api:whatsapp:send \
            --account-sid="${{ secrets.twilio_account_sid }}" \
            --to="whatsapp:${{ secrets.twilio_to_whatsapp_no }}" \
            --from="whatsapp:${{ secrets.twilio_from_whatsapp_no }}" \
            --message="$MESSAGE"
