name: Notifier

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  messageWhatsApp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Notification WhatsApp
        id: whatsapp-notify
        env:
          account_sid: ${{ secrets.twilio_account_sid }}
          auth_token: ${{ secrets.twilio_auth_token }}
          to_whatsapp_no: +50664694072,+50684297456
          message: "Se ha realizado un nuevo push en el repositorio X"
        uses: khaled-ibtikar/whatsapp-push-notify-action@master

