name: Notifier

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  messageWhatsApp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Notification WhatsApp
        id: whatsapp-notify
        env:
          account_sid: ${{ secrets.twilio_account_sid }}
          auth_token: ${{ secrets.twilio_auth_token }}
          message: "Se ha realizado un nuevo push en el repositorio X"

      - name: Send WhatsApp to Number 1
        run: |
          twilio api:core:messages:create \
            --from="whatsapp:${{ secrets.twilio_from_whatsapp_no }}" \
            --to="whatsapp:+50664694072" \
            --message-body="${{ env.message }}"
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.twilio_account_sid }}
          TWILIO_AUTH_TOKEN: ${{ secrets.twilio_auth_token }}

      - name: Send WhatsApp to Number 2
        run: |
          twilio api:core:messages:create \
            --from="whatsapp:${{ secrets.twilio_from_whatsapp_no }}" \
            --to="whatsapp:+50684297456" \
            --message-body="${{ env.message }}"
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.twilio_account_sid }}
          TWILIO_AUTH_TOKEN: ${{ secrets.twilio_auth_token }}


